## Question 3

### RRP SCARA

#### Homogeneous Transformations

In [2]:
import numpy as np

#Values for USER-INPUT
th1=30
th2=20
k3=0.5

#Pre Defined Values
r1=2;r2=1;r3=3  #Fixed Length between the joints

In [3]:
#Defining the Rotation Matrices
R0_1=np.array(([np.cos(th1),-np.sin(th1),0],
               [np.sin(th1),np.cos(th1),0],
               [0,0,1]))

R1_2=np.array(([np.cos(th2),-np.sin(th2),0],
               [np.sin(th2),np.cos(th2),0],
               [0,0,1]))

R2_3=np.array(([1,0,0],
               [0,1,0],
               [0,0,1]))

RL=[R0_1,R1_2,R2_3]

In [4]:
#Defining the translation matrices
d0_1=np.array(([0],
               [0],
               [0]))

d1_2=np.array(([0],
               [r2],
               [r1]))

d2_3=np.array(([0],
               [r3],
               [0]))

TL=[d0_1,d1_2,d2_3]

In [5]:
P3=np.array(([0],
             [0],
             [-k3],
             [1]))

In [6]:
#The below matrix creates a Homogeneos Transformation Matrix by taking into input the Rotation and Transllation Matices
def htrans(Rotation_Matrix,Translation_Matrix):
    htrans_mat=np.zeros((4,4))  #Initializing the Matrix as a Zero 4x4 Matrix
    htrans_mat[3,3]=1   #Updating the Scaling Factor as 
    
    #Augmenting a Matrix in Python -> https://chat.openai.com/share/0e9d93f2-7631-4313-85b1-2c922ffc1414
    htrans_mat[:3,:3]=Rotation_Matrix
    htrans_mat[:3,3:4]=Translation_Matrix

    return htrans_mat

In [7]:
Output=P3
for i in range(-1,-(len(RL)),-1):
    Output=np.dot(htrans(RL[i],TL[i]),Output)

In [8]:
Output

array([[-2.73883575],
       [ 2.22424619],
       [ 1.5       ],
       [ 1.        ]])

## Question 8

### RRP SCARA

#### Manipulator Jacobian

In [9]:
num_links=3

Output1=np.identity(4)
for i in range(-1,-(len(RL)),-1):
    Output1=np.dot(htrans(RL[i],TL[i]),Output1)

d3_0=Output1[0:3,3]
d3_0=d3_0.reshape(-1,1)

def mani_jaco(Rot_List,Trans_List,num_links):
    manipulator_jacobian=np.zeros((6,num_links))
    Output=np.identity(4)
    Output=np.dot(htrans(Rot_List[0],TL[0]),Output)
    d1_0=Output[0:3,3]
    K1=d3_0-d1_0
    MJ=np.dot(Rot_List[0],np.array(([0],[0],[1]))).reshape(-1,1)
    manipulator_jacobian[0:3,0]=np.cross(MJ[:, 0],K1[:, 0])
    manipulator_jacobian[3:6, 0] = np.dot(Rot_List[0], np.array(([[0], [0], [1]]))).flatten()

    R2_0=np.dot(RL[1],RL[0])
    R2_0m=np.dot(R2_0,np.array(([0],[0],[1])))
    for i in range(-2,-(len(Rot_List)),-1):
        Output=np.dot(htrans(Rot_List[i],TL[i]),Output)
    d2_0=Output[0:3,3]
    d2_0=d2_0.reshape(-1,1)
    K1=d3_0-d2_0
    manipulator_jacobian[0:3,1]=np.cross(R2_0m[:, 0],K1[:, 0])
    manipulator_jacobian[3:6,1] = np.dot(R2_0, np.array(([[0], [0], [1]]))).flatten()

    R3_0=np.dot(RL[2],R2_0)
    manipulator_jacobian[0:3,2] = np.dot(R3_0, np.array(([[0], [0], [1]]))).flatten()
    
    print(manipulator_jacobian)


In [10]:
mani_jaco(RL,TL,num_links)

[[-2.22424619 -1.22424619  0.        ]
 [-2.73883575 -2.73883575  0.        ]
 [ 0.          0.          1.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 1.          1.          0.        ]]


## Question 4

### RRP Standford

#### Homogeneous Transformations

In [11]:
import numpy as np

#Values for USER-INPUT
th1=30
th2=20
k3=0.5

#Pre Defined Values
r1=2;r2=1;r3=3  #Fixed Length between the joints

In [12]:
#Defining the Rotation Matrices
R0_1=np.array(([np.cos(th1),-np.sin(th1),0],
               [np.sin(th1),np.cos(th1),0],
               [0,0,1]))

R1_2=np.array(([np.cos(th2),-np.sin(th2),0],
               [0,0,1],
               [-np.sin(2),-np.cos(th2),0],))

R2_3=np.array(([1,0,0],
               [0,0,-1],
               [0,1,0]))

RL=[R0_1,R1_2,R2_3]

In [13]:
#Defining the translation matrices
d0_1=np.array(([0],
               [0],
               [0]))

d1_2=np.array(([0],
               [r2],
               [r1]))

d2_3=np.array(([0],
               [r3],
               [0]))

TL=[d0_1,d1_2,d2_3]

In [14]:
P3=np.array(([0],
             [0],
             [-k3],
             [1]))

In [15]:
Output=P3
for i in range(-1,-(len(RL)),-1):
    Output=np.dot(htrans(RL[i],TL[i]),Output)

In [16]:
Output

array([[-3.19530838],
       [ 1.        ],
       [ 0.57171278],
       [ 1.        ]])

## Question 10

### RRR

In [17]:
import numpy as np

#Values for USER-INPUT
th1=30
th2=20
th3=50

#Pre Defined Values
r1=2;r2=1;r3=3;r4=2;r5=1  #Fixed Length between the joints

In [18]:
R0_1=np.array(([np.cos(th1),-np.sin(th1),0],
               [np.sin(th1),np.cos(th1),0],
               [0,0,1]))

R1_2=np.array(([np.cos(th2),-np.sin(th2),0],
               [np.sin(th2),np.cos(th2),0],
               [0,0,1]))

R2_3=np.array(([np.cos(th3),-np.sin(th3),0],
               [np.sin(th3),np.cos(th3),0],
               [0,0,1]))

RL=[R0_1,R1_2,R2_3]

In [19]:
d0_1=np.array(([0],
               [0],
               [0]))

d1_2=np.array(([0],
               [r2],
               [r1]))

d2_3=np.array(([0],
               [r3],
               [r4]))

TL=[d0_1,d1_2,d2_3]

In [20]:
P3=np.array(([0],
             [0],
             [r5]))

#### Manipulator Jacobian

In [23]:
num_links=3

Output1=np.identity(4)
for i in range(-1,-(len(RL)),-1):
    Output1=np.dot(htrans(RL[i],TL[i]),Output1)

d3_0=Output1[0:3,3]
d3_0=d3_0.reshape(-1,1)

def mani_jaco(Rot_List,Trans_List,num_links):
    manipulator_jacobian=np.zeros((6,num_links))
    Output=np.identity(4)
    Output=np.dot(htrans(Rot_List[0],TL[0]),Output)
    d1_0=Output[0:3,3]
    K1=d3_0-d1_0
    MJ=np.dot(Rot_List[0],np.array(([0],[0],[1]))).reshape(-1,1)
    manipulator_jacobian[0:3,0]=np.cross(MJ[:, 0],K1[:, 0])
    manipulator_jacobian[3:6, 0] = np.dot(Rot_List[0], np.array(([[0], [0], [1]]))).flatten()

    R2_0=np.dot(RL[1],RL[0])
    R2_0m=np.dot(R2_0,np.array(([0],[0],[1])))
    for i in range(-2,-(len(Rot_List)),-1):
        Output=np.dot(htrans(Rot_List[i],TL[i]),Output)
    d2_0=Output[0:3,3]
    d2_0=d2_0.reshape(-1,1)
    K1=d3_0-d2_0
    manipulator_jacobian[0:3,1]=np.cross(R2_0m[:, 0],K1[:, 0])
    manipulator_jacobian[3:6,1] = np.dot(R2_0, np.array(([[0], [0], [1]]))).flatten()

    R3_0=np.dot(RL[2],R2_0)
    R3_0m=np.dot(R3_0,np.array(([0],[0],[1])))
    for i in range(-1,-(len(Rot_List)),-1):
        Output=np.dot(htrans(Rot_List[i],TL[i]),Output)
    d1_0=Output[0:3,3]
    d1_0=d1_0.reshape(-1,1)
    K1=d3_0-P3
    manipulator_jacobian[0:3,2]=np.cross(R3_0m[:, 0],K1[:, 0])
    manipulator_jacobian[3:6,2] = np.dot(R3_0, np.array(([[0], [0], [1]]))).flatten()

    print(manipulator_jacobian)


In [24]:
mani_jaco(RL,TL,num_links)

[[-2.22424619 -1.22424619 -2.22424619]
 [-2.73883575 -2.73883575 -2.73883575]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 1.          1.          1.        ]]
