Python Subroutine

For Quesstion 3

In [ ]:
import numpy as np

def manipulator_jacobian(l1,l2,q1,q2):
 link_lengths = l1,l2
 joint_angles = q1,q2

 z1=z2=z3= np.array([[0],
                     [0],
                     [1]])
 o1 = np.array([[0],
                [0],
                [0]])
 o2 = np.array([[l1*np.cos(q1)],
               [l1*np.sin(q1)],
               [0]])
 o3 = np.array([[l1*np.cos(q1)+l2*np.cos(q1+q2)],
               [l1*np.sin(q1)+l2*np.sin(q1+q2)],
               [0]])
 O1 = o3 - o1
 O1 = O1.ravel()
 z1a = z1.ravel()
 Z1a = np.cross(z1a,O1)
 Z1b = Z1a.reshape(-1,1)

 O2 = o3 - o2
 O2 = O2.ravel()
 z2b = z2.ravel()
 Z2a = np.cross(z2b,O2)
 Z2b = Z2a.reshape(-1,1)

 J1 = np.vstack((Z1b,z1))
 J2 = np.vstack((Z2b,z2))

 dh_params = np.array([[2, 0, 0, np.pi/4],
                       [3, 0, 0, np.pi/6]])
 # jacobian matrix
 J = np.hstack(([J1,J2]))
 J = manipulator_jacobian(2, dh_params)

 print(J)

Question 3

(a) Manipulator jacobian

In [5]:
import numpy as np

def manipulator_jacobian(l1, l2, q1, q2):
    # Define the DH parameters
    dh_params = np.array([
        [l1, 0, 0, q1],
        [l2, 0, 0, q2]
    ])

    # Initialize the Jacobian matrix
    J = np.zeros((6, 2))

    # Calculate the Jacobian matrix using DH parameters
    for i in range(2):
        a, d, alpha, theta = dh_params[i]
        z_i = np.array([0, 0, 1])
        p_i = np.array([a * np.cos(theta), a * np.sin(theta), d])
        o_i = np.cross(-z_i, p_i)

        J[:3, i] = o_i
        J[3:, i] = z_i

    return J

# Example usage
l1 = 2
l2 = 3
q1 = np.pi / 4
q2 = np.pi / 6

Jacobian = manipulator_jacobian(l1, l2, q1, q2)
print("Manipulator Jacobian:")
print(Jacobian)

Manipulator Jacobian:
[[ 1.41421356  1.5       ]
 [-1.41421356 -2.59807621]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 1.          1.        ]]


Question 3

(b) End effector position

In [6]:
import numpy as np

def manipulator_jacobian(l1, l2, q1, q2):
    # Define the DH parameters
    dh_params = np.array([
        [l1, 0, 0, q1],
        [l2, 0, 0, q2]
    ])

    # Initialize the Jacobian matrix
    J = np.zeros((6, 2))

    #Jacobian matrix using DH parameters
    for i in range(2):
        a, d, alpha, theta = dh_params[i]
        z_i = np.array([0, 0, 1])
        p_i = np.array([a * np.cos(theta), a * np.sin(theta), d])
        o_i = np.cross(-z_i, p_i)

        J[:3, i] = o_i
        J[3:, i] = z_i

    return J

# Example usage
l1 = 2
l2 = 3
q1 = np.pi / 4
q2 = np.pi / 6

#  Jacobian matrix
Jacobian = manipulator_jacobian(l1, l2, q1, q2)

# Define joint velocities (for example, in radian per second)
q1_dot = 0.1
q2_dot = 0.2
joint_velocities = np.array([q1_dot, q2_dot])

end_effector_velocity = np.dot(Jacobian, joint_velocities)

end_effector_position = np.zeros(3)  # Initialize the position vector
for i in range(2):
    end_effector_position += end_effector_velocity[i] * Jacobian[3:6, i]


# Print the end-effector position
print("End-effector position:")
print(end_effector_position)

End-effector position:
[ 0.          0.         -0.21961524]


Question 3

(c) End effector velocity

In [3]:
import numpy as np

def manipulator_jacobian(l1, l2, q1, q2):
    # Define the DH parameters
    dh_params = np.array([
        [l1, 0, 0, q1],
        [l2, 0, 0, q2]
    ])

    # Initialize the Jacobian matrix
    J = np.zeros((6, 2))

    #Jacobian matrix using DH parameters
    for i in range(2):
        a, d, alpha, theta = dh_params[i]
        z_i = np.array([0, 0, 1])
        p_i = np.array([a * np.cos(theta), a * np.sin(theta), d])
        o_i = np.cross(-z_i, p_i)

        J[:3, i] = o_i
        J[3:, i] = z_i

    return J

# Example usage
l1 = 2
l2 = 3
q1 = np.pi / 4
q2 = np.pi / 6

# Calculate the Jacobian matrix
Jacobian = manipulator_jacobian(l1, l2, q1, q2)

# Define joint velocities (for example, in radian per second)
q1_dot = 0.1
q2_dot = 0.2
joint_velocities = np.array([q1_dot, q2_dot])

#end-effector velocity using the Jacobian
end_effector_velocity = np.dot(Jacobian, joint_velocities)

# Print the end-effector velocity
print("End-effector velocity:")
print(end_effector_velocity)

End-effector velocity:
[ 0.44142136 -0.6610366   0.          0.          0.          0.3       ]


Question 4

Apply above code for STANDFORD MANIPULATOR

In [2]:
import numpy as np

def stanford_manipulator_rrp(q1, q2, d3, l1, l2):
    # Define the DH parameters for RRP configuration
    dh_params = np.array([
        [0, 0, 0, q1],
        [0, 0, 0, q2],
        [0, d3, 0, 0]
    ])

    # Initialize the Jacobian matrix
    J = np.zeros((6, 3))

    # Jacobian matrix using DH parameters
    for i in range(3):
        a, d, alpha, theta = dh_params[i]
        z_i = np.array([0, 0, 1])
        p_i = np.array([a * np.cos(theta), a * np.sin(theta), d])
        o_i = np.cross(-z_i, p_i)

        J[:3, i] = o_i
        J[3:, i] = z_i

    return J

# Example usage for Stanford RRP manipulator
q1 = np.pi / 4
q2 = np.pi / 6
d3 = 2
l1 = 1
l2 = 1

# Calculate the Jacobian matrix
Jacobian = stanford_manipulator_rrp(q1, q2, d3, l1, l2)

# Define joint velocities (for example, in radian per second)
q1_dot = 0.1
q2_dot = 0.2
d3_dot = 0.3
joint_velocities = np.array([q1_dot, q2_dot, d3_dot])

# end-effector velocity using the Jacobian
end_effector_velocity = np.dot(Jacobian, joint_velocities)

# Print the end-effector velocity
print("End-effector velocity for Stanford RRP manipulator:")
print(end_effector_velocity)


End-effector velocity for Stanford RRP manipulator:
[0.  0.  0.  0.  0.  0.6]


Question 4

Apply code of SCARA MANIPULATOR

In [1]:
import numpy as np

def scara_manipulator(q1, q2, l1, l2):
    # Define the DH parameters for SCARA configuration
    dh_params = np.array([
        [0, 0, 0, q1],
        [0, 0, l1, q2],
        [0, 0, 0, 0]
    ])

    # Initialize the Jacobian matrix
    J = np.zeros((6, 2))

    # Calculate the Jacobian matrix using DH parameters
    for i in range(2):
        a, d, alpha, theta = dh_params[i]
        z_i = np.array([0, 0, 1])
        p_i = np.array([a * np.cos(theta), a * np.sin(theta), d])
        o_i = np.cross(-z_i, p_i)

        J[:3, i] = o_i
        J[3:, i] = z_i

    return J

# Example usage for SCARA manipulator
q1 = np.pi / 4
q2 = np.pi / 6
l1 = 1
l2 = 1

# Calculate the Jacobian matrix
Jacobian = scara_manipulator(q1, q2, l1, l2)

# Define joint velocities (for example, in radian per second)
q1_dot = 0.1
q2_dot = 0.2
joint_velocities = np.array([q1_dot, q2_dot])

# Calculate the end-effector velocity using the Jacobian
end_effector_velocity = np.dot(Jacobian, joint_velocities)

# Print the end-effector velocity
print("End-effector velocity for SCARA manipulator:")
print(end_effector_velocity)


End-effector velocity for SCARA manipulator:
[0.  0.  0.  0.  0.  0.3]
